/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void Delay (void);
void GPIOxInit(void);

uint8_t interrupt_flag=0;

int main(void)
{
    GPIOxInit();
    //GPIO_Write_To_Output_Pin(GPIOA, GPIO_PIN_5, ENABLE);
    while (1)
    {
        if (interrupt_flag == 1)
        {
            void Delay (void);
            interrupt_flag = 0;
            GPIO_Toggle_Output_Pin(GPIOA, GPIO_PIN_5);
        }
    }

}

void EXTI15_10_IRQHandler (void)
{
    //*EXTI_PR |= (1 << 13);
    //interrupt_flag =1;
    GPIO_IRQHandling(GPIO_PIN_13);
    interrupt_flag = 1;
}

void Delay (void)
{
    uint32_t del_time;
    for (del_time=0; del_time<7000; del_time++);
}

void GPIOxInit(void)
{
    GPIO_Peripheral_Clock_Control(GPIOA, ENABLE);

    GPIO_Handle_t GPIOs_PORTA;
    GPIO_Handle_t GPIOs_PORTC;

    GPIOs_PORTA.GPIO_x = GPIOA;
    GPIOs_PORTA.GPIO_Config.GPIO_PinNumber = GPIO_PIN_5;
    GPIOs_PORTA.GPIO_Config.GPIO_PinMode = General_Purpose_Output;
    GPIOs_PORTA.GPIO_Config.GPIO_PinSpeed = LowSpeed;
    GPIOs_PORTA.GPIO_Config.GPIO_PinPUPDR = No_pullup_No_pulldown;
    GPIOs_PORTA.GPIO_Config.GPIO_PinOutput_Type = Push_Pull;
    GPIOs_PORTA.GPIO_Config.GPIO_PinAFR = AF0;

    GPIO_Init(&GPIOs_PORTA);


    GPIOs_PORTC.GPIO_x = GPIOC;
    GPIOs_PORTC.GPIO_Config.GPIO_PinNumber = GPIO_PIN_13;
    GPIOs_PORTC.GPIO_Config.GPIO_PinMode = Input_Interrupt_Falling;
    GPIOs_PORTC.GPIO_Config.GPIO_PinSpeed = LowSpeed;
    GPIOs_PORTC.GPIO_Config.GPIO_PinPUPDR = No_pullup_No_pulldown;

    GPIO_Init(&GPIOs_PORTC);

    GPIO_IRQInterruptConfig(EXTI15_10_IRQn, ENABLE);

}
