#ifndef INIT_H
#define INIT_H


#define RCC_BASE_ADD  0x40023800
#define RCC_CR_OFFSET 0x0
#define RCC_CR_ADD (RCC_BASE_ADD + RCC_CR_OFFSET)
#define RCC_AHB1ENR_OFFSET  0x30
#define RCC_AHB1ENR_ADD  (RCC_BASE_ADD + RCC_AHB1ENR_OFFSET)
#define RCC_APB2ENR_OFFSET 0x44
#define RCC_APB2ENR_ADD (RCC_BASE_ADD + RCC_APB2ENR_OFFSET)
#define RCC_CFGR_OFFSET 0x08
#define RCC_CFGR_ADD   (RCC_BASE_ADD + RCC_CFGR_OFFSET)
#define RCC_PLLCFGR_OFFSET      0x04
#define RCC_PLLCFGR_ADD (RCC_BASE_ADD + RCC_PLLCFGR_OFFSET)


#define GPIOA_BASE_ADD     0x40020000
#define GPIOA_MODER_OFFSET       0x00
#define GPIOA_MODER_ADD  (GPIOA_BASE_ADD + GPIOA_MODER_OFFSET)

#define GPIOC_BASE_ADD     0x40020800 //0x4002 0800
#define GPIOC_MODER_OFFSET       0x00
#define GPIOC_MODER_ADD  (GPIOC_BASE_ADD + GPIOC_MODER_OFFSET)
#define GPIOC_AFRH_OFFSET       0x24
#define GPIOC_AFRH_ADD   (GPIOC_BASE_ADD + GPIOC_AFRH_OFFSET)


void configure_PC9_as_MCO(void);
void select_HSI_as_SYSCLK(void);
#endif // INIT_H
