/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RCC_BASE_ADD  0x40023800
#define RCC_AHB1ENR_OFFSET  0x30
#define RCC_AHB1ENR_ADD  (RCC_BASE_ADD + RCC_AHB1ENR_OFFSET)

#define RCC_APB2ENR_OFFSET 0x44
#define RCC_APB2ENR_ADD (RCC_BASE_ADD + RCC_APB2ENR_OFFSET)



#define GPIOA_BASE_ADD     0x40020000
#define GPIOA_MODER_OFFSET       0x00
#define GPIOA_MODER_ADD  (GPIOA_BASE_ADD + GPIOA_MODER_OFFSET)
#define GPIOA_ODR_OFFSET         0x14
#define GPIOA_ODR_ADD    (GPIOA_BASE_ADD + GPIOA_ODR_OFFSET)


#define GPIOC_BASE_ADD     0x40020800 //0x4002 0800
#define GPIOC_MODER_OFFSET       0x00
#define GPIOC_MODER_ADD  (GPIOC_BASE_ADD + GPIOC_MODER_OFFSET)
#define GPIOC_ODR_OFFSET         0x14
#define GPIOC_ODR_ADD    (GPIOC_BASE_ADD + GPIOC_ODR_OFFSET)

#define SYSCFG_BASE_ADD 0x40013800 //0x4001 3800
#define SYSCFG_EXTICR4_OFFSET 0x14
#define SYSCFG_EXTICR4_ADD  (SYSCFG_BASE_ADD + SYSCFG_EXTICR4_OFFSET)

#define EXTI_BASE_ADD 0x40013C00 //0x4001 3C00
#define EXTI_IMR_OFFSET  0x00
#define EXTI_IMR_ADD (EXTI_BASE_ADD + EXTI_IMR_OFFSET)
#define EXTI_RTSR_OFFSET 0x08
#define EXTI_RTSR_ADD (EXTI_BASE_ADD + EXTI_RTSR_OFFSET)
#define EXTI_PR_OFFSET 0x14
#define EXTI_PR_ADD (EXTI_BASE_ADD + EXTI_PR_OFFSET)

#define NVIC_ISER0_BASE_ADD 0xE000E100
#define NVIC_ISER1_BASE_ADD 0xE000E104



void LED_blink_init(void);

void Button_Init(void);
void Delay (void);


//Create a pointer to enable registers

volatile uint32_t * RCC_AHB1ENR = (volatile uint32_t*) RCC_AHB1ENR_ADD;
volatile uint32_t * GPIOA_ODR   = (volatile uint32_t*) GPIOA_ODR_ADD;

volatile uint32_t * EXTI_PR     = (volatile uint32_t*) EXTI_PR_ADD;


uint8_t interrupt_flag=0;



int main(void)
{
	LED_blink_init();
	Button_Init();

	while(1)
	{
		if(interrupt_flag)
		{
			Delay();
			*GPIOA_ODR ^=(1<<5);
			interrupt_flag = 0;
		}
	}

}

void LED_blink_init(void)
{
	volatile uint32_t * GPIOA_MODER = (volatile uint32_t*) GPIOA_MODER_ADD;

	*RCC_AHB1ENR |= 0x01; //IO port A clock enable
	//clean register before set
	*GPIOA_MODER &= ~(3 << 10); // 0xffff f3ff
	*GPIOA_MODER |= (1<< 10);  //PA5 is output (01)

	*GPIOA_ODR ^= (1<<5);


}

void Button_Init(void)
{
	volatile uint32_t * RCC_AHB1ENR    = (volatile uint32_t *) RCC_AHB1ENR_ADD;
	volatile uint32_t * GPIOC_MODER    = (volatile uint32_t *) GPIOC_MODER_ADD;
	//volatile uint32_t * GPIOC_ODR      = (volatile uint32_t *) GPIOC_ODR_ADD;
	volatile uint32_t * RCC_APB2ENR    = (volatile uint32_t *) RCC_APB2ENR_ADD;
	volatile uint32_t * SYSCFG_EXTICR4 = (volatile uint32_t *) SYSCFG_EXTICR4_ADD;
	volatile uint32_t * EXTI_IMR       = (volatile uint32_t *) EXTI_IMR_ADD;
	volatile uint32_t * EXTI_RTSR      = (volatile uint32_t *) EXTI_RTSR_ADD;
	//volatile uint32_t * NVIC_ISER0     = (volatile uint32_t *) NVIC_ISER0_BASE_ADD;
	volatile uint32_t * NVIC_ISER1     = (volatile uint32_t *) NVIC_ISER1_BASE_ADD;


	*RCC_AHB1ENR |= (1<<2); //IO port C clock enable

	// clean register before set, this the desired configuration
	*GPIOC_MODER &= ~(3 <<26); //PC13 is input



	*RCC_APB2ENR |= (1<<14); //SYSCFGEN  System configuration controller clock enable set to 1

	*SYSCFG_EXTICR4 &=  ~(15 << 4); // clean EXTI13[3:0] from SYSCFG_EXTICR4
	*SYSCFG_EXTICR4 |= (0x2 << 4); //0x2 = 0010: PC[x] pin, 4 bits shift to configure PC13



	*EXTI_IMR |= (0x1<<13);  //Event request from line 13 is not masked
	*EXTI_RTSR |= (0x1<<13); //Rising trigger enabled (for Event and Interrupt) for input line 13

	*NVIC_ISER1 |= (0x01 << 8); //Position 40 of vector Table, corresponds to ISER 1 bit (40-32) = 8}
}

void EXTI15_10_IRQHandler (void)
{
	*EXTI_PR |= (1 << 13);
	interrupt_flag =1;
}

void Delay (void)
{
	uint32_t del_time;
	for (del_time=0; del_time<7000; del_time++);
}


